### ISSUE TITLE
Please fix issue with type float

### ISSUE THREAD

**Issue by Alexandeer** [lobianco/ALAlertBanner#40]
ALAlertBanner.m:76:22: Incompatible pointer types sending 'float *' to parameter of type 'CGFloat *' (aka 'double *')
Need replace float to CGFloat

**Comment by EwyynTomato** [comment]
This is actually already fix in the [HEAD commit from this pull request](https://github.com/alobi/ALAlertBanner/commit/756cea2d05f01d6f3b0e01b970beac3045a0cc67)

For a quick fix on your machine, please refer to my other comment in the related issue: https://github.com/alobi/ALAlertBanner/issues/38#issuecomment-95480440
